apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }} 
  namespace: {{ include "resource.default.name" . }}
  labels:
    app: {{ include "resource.default.name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "resource.default.name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "resource.default.name" . }}
    spec:
      serviceAccountName: {{ include "resource.default.name" . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ include "resource.default.name" . }}
        env:
        - name: VAULT_ADDR
          value: '{{ .Values.Installation.V1.Auth.Vault.Address }}'
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
        - "--vault-tls-cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        livenessProbe:
          httpGet:
            path: /
            port: 9410
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
          - name: http
            containerPort: 9410
