version: 2.1

orbs:
  architect: giantswarm/architect@0.10.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-vault-exporter
          binary: vault-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-vault-exporter-to-quay
          image: "quay.io/giantswarm/vault-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-vault-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-vault-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/vault-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-vault-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-vault-exporter-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "vault-exporter"
          # Make sure docker image is successfully built.
          requires:
            - push-vault-exporter-to-quay
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-vault-exporter-to-aws-app-collection
          app_name: "vault-exporter"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-vault-exporter-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-vault-exporter-to-azure-app-collection
          app_name: "vault-exporter"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-vault-exporter-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-vault-exporter-to-kvm-app-collection
          app_name: "vault-exporter"
          app_collection_repo: "kvm-app-collection"
          unique: "true"
          requires:
            - push-vault-exporter-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
